name: Lighthouse
on: [pull_request]

jobs:
  score-check:
    runs-on: ubuntu-latest
    steps:
    # Wait for the preview deployed by Netlify
    - name: Wait for preview deployed
      uses: jakepartusch/wait-for-netlify-action@v1.3
      id: preview
      with:
        site_name: "toha"
        max_timeout: 300

    # Run Lighthouse check
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@v8.0.2
      id: lighthouseCheck
      with:
        accessToken: ${{ secrets.LIGHTHOUSE_TOKEN }}
        emulatedFormFactor: 'all'
        prCommentEnabled: true
        urls: "${{ steps.preview.outputs.url }},${{ steps.preview.outputs.url }}/posts/,${{ steps.preview.outputs.url }}/posts/markdown-sample/"

    # Verify Lighthouse scores
    - name: Verify Lighthouse  scores
      uses: foo-software/lighthouse-check-status-action@v1.0.1
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "95"
        minBestPracticesScore: "85"
        minPerformanceScore: "60"
        minProgressiveWebAppScore: "50"
        minSeoScore: "90"
