name: Percy.io Visual Diff

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # install hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: '0.77.0'
          # extended: true

      # build the site
      - name: Build
        run: hugo --minify

      # run percy test
      - name: Percy Test
        uses: percy/snapshot-action@v0.1.2
        with:
          build-directory: "public"
          flags: --config=./.percy.yml
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
